services:
  db:
    image: postgres:17-alpine3.20
    container_name: pgsql
    volumes:
      - ./.postgres/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
